baseURL = "https://dazzling-lamport-a78cb3.netlify.com/"
languageCode = "en-us"
title = "Tangent Blog"
theme = "hugo-nuo"
canonifyURLs = true
enableRobotsTXT = true
[taxonomies]
  category = "categories"
  tag = "tags"